### ISSUE TITLE
User bearbeiten für Taskforce zeigt leere Seite wenn aus Helferliste aufgerufen

### ISSUE THREAD

**Issue by Lockenjoe92** [Lockenjoe92/UKT-COVID19-Helpermanagement#141]

**Comment by Lockenjoe92** [comment]
Fatal error: Uncaught Error: Call to undefined function emtpy() in /www/htdocs/w01a6506/helfer.fachschaftmedizin.de/taskforce_edit_user_functions/taskforce_edit_user_functions.php:25 Stack trace: #0 /www/htdocs/w01a6506/helfer.fachschaftmedizin.de/taskforce_edit_user_functions/taskforce_edit_user_functions.php(13): taskforce_user_bearbeiten_ansicht('87', 'https://helfer....') #1 /www/htdocs/w01a6506/helfer.fachschaftmedizin.de/taskforce_edit_user.php(7): taskforce_edit_user_content_generator('87', 'https://helfer....') #2 {main} thrown in /www/htdocs/w01a6506/helfer.fachschaftmedizin.de/taskforce_edit_user_functions/taskforce_edit_user_functions.php on line 25
